#!/bin/sh
set -eu
cd "$(git rev-parse --show-toplevel)"
while read -r local_ref local_oid remote_ref remote_oid; do
  case "$local_oid" in ''|*[!0]*) ;; *) continue ;; esac
  python3 tools/check_public_files.py --history "$local_oid"
done
